# Все промпты на 6 языков

LANG_NAMES = {
    "ru": "русском",
    "de": "немецком",
    "en": "английском",
    "uk": "украинском",
    "ar": "арабском",
    "ps": "пашто"
}

MESSAGES = {
    "ru": {
        "welcome": "👋 Привет! Я — Job Hunter Germany.\nПомогу найти работу в Германии (DACH регион).\n\nВыбери язык:",
        "upload_cv": "Отлично! Теперь загрузи своё резюме в формате PDF или вставь текст прямо сюда.",
        "parsing": "⏳ Анализирую резюме...",
        "parsed_ok": "✅ Резюме проанализировано!\n\nВот что я нашёл:\n📌 Профиль: {domain}\n💡 Скрытые компетенции: {hidden}\n🎯 Возможности в DACH: {opportunities}\n\nТеперь задам несколько уточняющих вопросов.",
        "question": "❓ Вопрос {n} из {total}:\n\n{question}",
        "searching": "🔍 Ищу подходящие компании рядом с вами...",
        "companies_found": "✅ Нашёл {count} компаний!\n\n{list}\n\nКакие компании вас интересуют? Напиши номера через запятую (например: 1, 3, 5)",
        "no_companies": "😔 Не нашёл компаний по вашему профилю. Попробуем расширить поиск.",
        "adapting": "⚙️ Адаптирую резюме под {company}...",
        "writing_email": "✍️ Составляю письмо для {company}...",
        "review_letter": "📄 Вот документы для {company}:\n\n🇩🇪 РЕЗЮМЕ (немецкий):\n{lebenslauf_de}\n\n✉️ ПИСЬМО (немецкий):\n{anschreiben_de}\n\n📋 ПЕРЕВОД ПИСЬМА:\n{anschreiben_user}\n\nОтправить это письмо? (да / нет / поправить)",
        "confirm_send": "На какой email отправить письмо в {company}?",
        "sending": "📤 Отправляю письмо...",
        "sent_ok": "✅ Письмо отправлено в {company}!\n\nНапомню через 3 дня если не будет ответа.",
        "sent_error": "❌ Ошибка отправки. Проверь email адрес.",
        "followup_1": "🔔 Прошло 3 дня после отправки в {company}. Отправить напоминание? (да / нет)",
        "followup_2": "🔔 Прошло 7 дней после отправки в {company}. Отправить последнее напоминание? (да / нет)",
        "followup_sent": "✅ Напоминание отправлено в {company}.",
        "next_company": "Обработать следующую компанию?",
        "done": "🎉 Готово! Письма отправлены в {count} компаний.\n\nУдачи с поиском работы! 🍀",
        "error": "😔 Что-то пошло не так. Попробуй ещё раз.",
        "enter_email": "Введи email работодателя:",
    },
    "de": {
        "welcome": "👋 Hallo! Ich bin Job Hunter Germany.\nIch helfe dir, einen Job in der DACH-Region zu finden.\n\nWähle deine Sprache:",
        "upload_cv": "Super! Lade deinen Lebenslauf als PDF hoch oder füge den Text hier ein.",
        "parsing": "⏳ Analysiere Lebenslauf...",
        "parsed_ok": "✅ Lebenslauf analysiert!\n\n📌 Profil: {domain}\n💡 Versteckte Kompetenzen: {hidden}\n🎯 Chancen in DACH: {opportunities}\n\nIch stelle jetzt einige Fragen.",
        "question": "❓ Frage {n} von {total}:\n\n{question}",
        "searching": "🔍 Suche passende Unternehmen in Ihrer Nähe...",
        "companies_found": "✅ {count} Unternehmen gefunden!\n\n{list}\n\nWelche Unternehmen interessieren Sie? Schreiben Sie Nummern durch Komma (z.B.: 1, 3, 5)",
        "no_companies": "😔 Keine Unternehmen gefunden. Wir versuchen eine breitere Suche.",
        "adapting": "⚙️ Passe Lebenslauf für {company} an...",
        "writing_email": "✍️ Schreibe Anschreiben für {company}...",
        "review_letter": "📄 Dokumente für {company}:\n\n🇩🇪 LEBENSLAUF:\n{lebenslauf_de}\n\n✉️ ANSCHREIBEN:\n{anschreiben_de}\n\n📋 ÜBERSETZUNG:\n{anschreiben_user}\n\nDiesen Brief absenden? (ja / nein / korrigieren)",
        "confirm_send": "An welche E-Mail soll der Brief an {company} gesendet werden?",
        "sending": "📤 Sende Brief...",
        "sent_ok": "✅ Brief an {company} gesendet!\n\nIch erinnere in 3 Tagen falls keine Antwort.",
        "sent_error": "❌ Sendefehler. Bitte E-Mail-Adresse prüfen.",
        "followup_1": "🔔 3 Tage seit Bewerbung bei {company}. Erinnerung senden? (ja / nein)",
        "followup_2": "🔔 7 Tage seit Bewerbung bei {company}. Letzte Erinnerung senden? (ja / nein)",
        "followup_sent": "✅ Erinnerung an {company} gesendet.",
        "next_company": "Nächstes Unternehmen bearbeiten?",
        "done": "🎉 Fertig! Briefe an {count} Unternehmen gesendet.\n\nViel Erfolg! 🍀",
        "error": "😔 Etwas ist schiefgelaufen. Bitte erneut versuchen.",
        "enter_email": "E-Mail des Arbeitgebers eingeben:",
    },
    "en": {
        "welcome": "👋 Hello! I am Job Hunter Germany.\nI'll help you find a job in the DACH region.\n\nChoose your language:",
        "upload_cv": "Great! Upload your CV as PDF or paste the text here.",
        "parsing": "⏳ Analyzing CV...",
        "parsed_ok": "✅ CV analyzed!\n\n📌 Profile: {domain}\n💡 Hidden competencies: {hidden}\n🎯 DACH opportunities: {opportunities}\n\nI'll ask a few clarifying questions now.",
        "question": "❓ Question {n} of {total}:\n\n{question}",
        "searching": "🔍 Searching for matching companies near you...",
        "companies_found": "✅ Found {count} companies!\n\n{list}\n\nWhich companies interest you? Enter numbers separated by commas (e.g.: 1, 3, 5)",
        "no_companies": "😔 No companies found for your profile. Let's try a broader search.",
        "adapting": "⚙️ Adapting CV for {company}...",
        "writing_email": "✍️ Writing application letter for {company}...",
        "review_letter": "📄 Documents for {company}:\n\n🇩🇪 CV (German):\n{lebenslauf_de}\n\n✉️ LETTER (German):\n{anschreiben_de}\n\n📋 TRANSLATION:\n{anschreiben_user}\n\nSend this letter? (yes / no / edit)",
        "confirm_send": "What email should the letter to {company} be sent to?",
        "sending": "📤 Sending letter...",
        "sent_ok": "✅ Letter sent to {company}!\n\nI'll remind you in 3 days if no reply.",
        "sent_error": "❌ Send error. Please check the email address.",
        "followup_1": "🔔 3 days since application to {company}. Send reminder? (yes / no)",
        "followup_2": "🔔 7 days since application to {company}. Send final reminder? (yes / no)",
        "followup_sent": "✅ Reminder sent to {company}.",
        "next_company": "Process next company?",
        "done": "🎉 Done! Letters sent to {count} companies.\n\nGood luck! 🍀",
        "error": "😔 Something went wrong. Please try again.",
        "enter_email": "Enter employer email:",
    },
    "uk": {
        "welcome": "👋 Привіт! Я — Job Hunter Germany.\nДопоможу знайти роботу в DACH регіоні.\n\nОбери мову:",
        "upload_cv": "Чудово! Завантаж своє резюме у форматі PDF або вставте текст сюди.",
        "parsing": "⏳ Аналізую резюме...",
        "parsed_ok": "✅ Резюме проаналізовано!\n\n📌 Профіль: {domain}\n💡 Приховані компетенції: {hidden}\n🎯 Можливості в DACH: {opportunities}\n\nТепер задам кілька уточнюючих питань.",
        "question": "❓ Питання {n} з {total}:\n\n{question}",
        "searching": "🔍 Шукаю підходящі компанії поруч з вами...",
        "companies_found": "✅ Знайшов {count} компаній!\n\n{list}\n\nЯкі компанії вас цікавлять? Напиши номери через кому (наприклад: 1, 3, 5)",
        "no_companies": "😔 Не знайшов компаній за вашим профілем. Спробуємо розширити пошук.",
        "adapting": "⚙️ Адаптую резюме під {company}...",
        "writing_email": "✍️ Складаю листа для {company}...",
        "review_letter": "📄 Документи для {company}:\n\n🇩🇪 РЕЗЮМЕ (німецька):\n{lebenslauf_de}\n\n✉️ ЛИСТ (німецька):\n{anschreiben_de}\n\n📋 ПЕРЕКЛАД:\n{anschreiben_user}\n\nВідправити цього листа? (так / ні / виправити)",
        "confirm_send": "На який email відправити листа до {company}?",
        "sending": "📤 Відправляю листа...",
        "sent_ok": "✅ Листа відправлено до {company}!\n\nНагадаю через 3 дні якщо не буде відповіді.",
        "sent_error": "❌ Помилка відправки. Перевір email адресу.",
        "followup_1": "🔔 Минуло 3 дні після відправки до {company}. Відправити нагадування? (так / ні)",
        "followup_2": "🔔 Минуло 7 днів після відправки до {company}. Відправити останнє нагадування? (так / ні)",
        "followup_sent": "✅ Нагадування відправлено до {company}.",
        "next_company": "Обробити наступну компанію?",
        "done": "🎉 Готово! Листи відправлено до {count} компаній.\n\nУдачі з пошуком роботи! 🍀",
        "error": "😔 Щось пішло не так. Спробуй ще раз.",
        "enter_email": "Введи email роботодавця:",
    },
    "ar": {
        "welcome": "👋 مرحباً! أنا Job Hunter Germany.\nسأساعدك في إيجاد عمل في منطقة DACH.\n\nاختر لغتك:",
        "upload_cv": "رائع! قم بتحميل سيرتك الذاتية بصيغة PDF أو الصق النص هنا.",
        "parsing": "⏳ جارٍ تحليل السيرة الذاتية...",
        "parsed_ok": "✅ تم تحليل السيرة الذاتية!\n\n📌 الملف: {domain}\n💡 الكفاءات الخفية: {hidden}\n🎯 الفرص في DACH: {opportunities}\n\nسأطرح بعض الأسئلة التوضيحية.",
        "question": "❓ سؤال {n} من {total}:\n\n{question}",
        "searching": "🔍 البحث عن شركات مناسبة بالقرب منك...",
        "companies_found": "✅ وجدت {count} شركة!\n\n{list}\n\nأي الشركات تهمك؟ اكتب الأرقام مفصولة بفواصل (مثال: 1, 3, 5)",
        "no_companies": "😔 لم أجد شركات لملفك الشخصي. دعنا نوسع البحث.",
        "adapting": "⚙️ تكييف السيرة الذاتية لـ {company}...",
        "writing_email": "✍️ كتابة خطاب التقديم لـ {company}...",
        "review_letter": "📄 الوثائق لـ {company}:\n\n🇩🇪 السيرة الذاتية (بالألمانية):\n{lebenslauf_de}\n\n✉️ الخطاب (بالألمانية):\n{anschreiben_de}\n\n📋 الترجمة:\n{anschreiben_user}\n\nإرسال هذا الخطاب؟ (نعم / لا / تعديل)",
        "confirm_send": "إلى أي بريد إلكتروني يجب إرسال الخطاب إلى {company}؟",
        "sending": "📤 جارٍ الإرسال...",
        "sent_ok": "✅ تم إرسال الخطاب إلى {company}!\n\nسأذكرك بعد 3 أيام إذا لم يكن هناك رد.",
        "sent_error": "❌ خطأ في الإرسال. يرجى التحقق من البريد الإلكتروني.",
        "followup_1": "🔔 مرت 3 أيام منذ التقديم إلى {company}. إرسال تذكير؟ (نعم / لا)",
        "followup_2": "🔔 مرت 7 أيام منذ التقديم إلى {company}. إرسال آخر تذكير؟ (نعم / لا)",
        "followup_sent": "✅ تم إرسال التذكير إلى {company}.",
        "next_company": "معالجة الشركة التالية؟",
        "done": "🎉 تم! تم إرسال الرسائل إلى {count} شركة.\n\nحظاً موفقاً! 🍀",
        "error": "😔 حدث خطأ ما. يرجى المحاولة مرة أخرى.",
        "enter_email": "أدخل البريد الإلكتروني لصاحب العمل:",
    },
    "ps": {
        "welcome": "👋 سلام! زه Job Hunter Germany یم.\nزه به تاسو سره د DACH سیمه کې د کار موندلو کې مرسته وکړم.\n\nژبه غوره کړئ:",
        "upload_cv": "ښه! خپل CV د PDF په توګه آپلوډ کړئ یا متن دلته پیسټ کړئ.",
        "parsing": "⏳ CV تحلیلوم...",
        "parsed_ok": "✅ CV تحلیل شو!\n\n📌 پروفایل: {domain}\n💡 پټې وړتیاوې: {hidden}\n🎯 د DACH فرصتونه: {opportunities}\n\nاوس به یو څو پوښتنې وکړم.",
        "question": "❓ پوښتنه {n} له {total} څخه:\n\n{question}",
        "searching": "🔍 ستاسو سره نږدې مناسبې شرکتونه لټوم...",
        "companies_found": "✅ {count} شرکتونه وموندل شول!\n\n{list}\n\nکوم شرکتونه تاسو ته علاقه لري؟ شمیرې د کوما سره ولیکئ (لکه: 1, 3, 5)",
        "no_companies": "😔 ستاسو پروفایل لپاره شرکتونه ونه موندل شول. لټون پراخوو.",
        "adapting": "⚙️ د {company} لپاره CV تطبیقوم...",
        "writing_email": "✍️ د {company} لپاره لیک لیکم...",
        "review_letter": "📄 د {company} لپاره اسناد:\n\n🇩🇪 CV (جرمني):\n{lebenslauf_de}\n\n✉️ لیک (جرمني):\n{anschreiben_de}\n\n📋 ژباړه:\n{anschreiben_user}\n\nدا لیک واستوئ؟ (هو / نه / سمول)",
        "confirm_send": "د {company} لپاره لیک کومه بریښنالیک ته واستول شي؟",
        "sending": "📤 لیک استوم...",
        "sent_ok": "✅ لیک {company} ته واستول شو!\nکه ځواب ونه وي نو 3 ورځې وروسته به درته یادونه وکړم.",
        "sent_error": "❌ د لیږلو تیروتنه. مهرباني وکړئ بریښنالیک وګورئ.",
        "followup_1": "🔔 د {company} درخواست وروسته 3 ورځې تیرې شوې. یادونه واستوئ؟ (هو / نه)",
        "followup_2": "🔔 د {company} درخواست وروسته 7 ورځې تیرې شوې. وروستۍ یادونه واستوئ؟ (هو / نه)",
        "followup_sent": "✅ یادونه {company} ته واستول شوه.",
        "next_company": "بله شرکت پروسس کړئ؟",
        "done": "🎉 بشپړ! لیکونه {count} شرکتونو ته واستول شول.\n\nبریالیتوب مو وغواړم! 🍀",
        "error": "😔 یو شی غلط شو. بیا هڅه وکړئ.",
        "enter_email": "د کارموندونکي بریښنالیک دننه کړئ:",
    }
}

def get_message(lang: str, key: str, **kwargs) -> str:
    """Возвращает сообщение на нужном языке с подстановкой переменных."""
    lang = lang if lang in MESSAGES else "ru"
    template = MESSAGES[lang].get(key, MESSAGES["ru"].get(key, key))
    if kwargs:
        try:
            return template.format(**kwargs)
        except Exception:
            return template
    return template
